# Generated by Django 2.0.9 on 2024-02-20 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='caretaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='caretaker_reuqest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('CARETAKER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='door_of_hope_app.caretaker')),
            ],
        ),
        migrations.CreateModel(
            name='donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('items', models.CharField(max_length=200)),
                ('count', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='donation_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('DONATION', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='door_of_hope_app.donation')),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('usertype', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='medicine_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('statuss', models.CharField(max_length=200)),
                ('medicine', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=200)),
                ('CARETAKER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='door_of_hope_app.caretaker')),
            ],
        ),
        migrations.CreateModel(
            name='photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('photo', models.CharField(max_length=200)),
                ('program_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('reminder', models.CharField(max_length=200)),
                ('reminder_date', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('details', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='sponsorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(max_length=200)),
                ('medical_history', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('need', models.CharField(max_length=200)),
                ('house_name', models.CharField(max_length=200)),
                ('postal', models.CharField(max_length=200)),
                ('pin', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='sponsorship_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('statuss', models.CharField(max_length=200)),
                ('detailss', models.CharField(max_length=200)),
                ('SPONSORSHIP', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='door_of_hope_app.sponsorship')),
            ],
        ),
        migrations.CreateModel(
            name='suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('suggestions', models.CharField(max_length=200)),
                ('CARETAKER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='door_of_hope_app.caretaker')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('relation', models.CharField(max_length=200)),
                ('patient_name', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=200)),
                ('medical_history', models.CharField(max_length=200)),
                ('house', models.CharField(max_length=200)),
                ('post', models.CharField(max_length=200)),
                ('pincode', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('LOGIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='door_of_hope_app.login')),
            ],
        ),
        migrations.AddField(
            model_name='sponsorship_request',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='door_of_hope_app.user'),
        ),
        migrations.AddField(
            model_name='reports',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='door_of_hope_app.user'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='door_of_hope_app.user'),
        ),
        migrations.AddField(
            model_name='donation_request',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='door_of_hope_app.user'),
        ),
        migrations.AddField(
            model_name='caretaker_reuqest',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='door_of_hope_app.user'),
        ),
        migrations.AddField(
            model_name='caretaker',
            name='LOGIN',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='door_of_hope_app.login'),
        ),
    ]
